"""
FULLY-ONLINE on-policy selection-distillation (2 GPUs, streaming).

  GPU0: ACTOR  (MolmoWeb-4B + LoRA, trainable + optimizer)  -- generates AND trains
  GPU1: SELECTOR (merged all-linear arbiter, vLLM, frozen)   -- picks best-of-5

Loop, per batch of states (cycling the pool):
  1. actor.generate(n=5, temp 1.0)         on-policy candidates from CURRENT weights  [GPU0]
  2. selector picks best-of-5 per state     (catts_vision_select_v2 via vLLM)         [GPU1]
  3. one SFT gradient step on {prompt -> selected action}                              [GPU0]
  -> next batch is generated by the just-updated actor (fully on-policy).

This is a SCAFFOLD: structurally faithful, not yet GPU-smoke-tested. The device split,
the molmo generate/train interleave, and selection latency are the parts to validate first
(run with --smoke for a few batches).

Env: ACTOR_MODEL, ACTOR_REVISION, ARBITER_DIR, STATES, OUT, BATCH, LR, EPOCHS,
     LORA_TARGETS, LORA_EXCLUDE, KL_COEF (0 = off; >0 anchors to the frozen base actor).
"""
import os, json, subprocess, time, random, asyncio, atexit
import requests, torch
import torch.nn.functional as F
from transformers import AutoProcessor, AutoModelForImageTextToText
from peft import LoraConfig, get_peft_model
from PIL import Image
from openai import OpenAI
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "inference"))
from selection_prompt import catts_vision_select_v2, ArbiterCandidate  # repo-canonical builder
from eval.agents import MolmoWebAgent   # for _parse_molmo_output (action_str parity)

# selector prompt config (this repo's builder supports only the no-CoT variant)
for _k, _v in {
    "CATTS_VISION_PROMPT_V2": "1", "CATTS_VISION_COLORED": "1", "CATTS_VISION_MAX_TOKENS": "16384",
    "VISION_NO_SOM": "1", "VISION_ABLATE_DOM": "1", "VISION_ABLATE_VOTES": "1",
    "NORMALIZE_COORDS": "1", "CLUSTER_NO_DOM": "1", "VISION_NO_COT": "1",
}.items():
    os.environ.setdefault(_k, _v)

ACTOR_MODEL = os.environ.get("ACTOR_MODEL", "allenai/MolmoWeb-4B")
REVISION = os.environ.get("ACTOR_REVISION", "refs/pr/1")
ARBITER_DIR = os.environ.get("ARBITER_DIR", "output/prm_offline_pilot/train_full/merged_alllinear_3894")
STATES_PATH = os.environ.get("STATES", "output/onpolicy/round0/states.jsonl")
OUT = os.environ.get("OUT", "output/onpolicy/online")
N = 5
BATCH = int(os.environ.get("BATCH", "16"))
LR = float(os.environ.get("LR", "1e-5"))
EPOCHS = int(os.environ.get("EPOCHS", "1"))
KL_COEF = float(os.environ.get("KL_COEF", "0.0"))
SMOKE = os.environ.get("SMOKE") == "1"
PORT = 8994; SEL_NAME = "q4b-al"
ACTOR_DEV = "cuda:0"
os.makedirs(OUT, exist_ok=True)

# ---------------- selector: vLLM subprocess on GPU1 ----------------
def serve_selector():
    # actor runs in molmoweb conda; vLLM serving is done via the SIF container.
    # singularity --nv exposes ALL node GPUs, so we must pin to the ACTUAL 2nd GPU id
    # SGE allocated (the 2nd entry of the parent's CUDA_VISIBLE_DEVICES), not a literal "1".
    SIF = os.environ.get("SIF", "/projectnb/ivc-ml/piotrt/sif/vllm-0.19.1.sif")
    vis = [x for x in os.environ.get("CUDA_VISIBLE_DEVICES", "0,1").split(",") if x != ""]
    sel_gpu = vis[1] if len(vis) > 1 else vis[0]
    cmd = ["singularity", "exec", "--nv", "-B", "/projectnb/ivc-ml/piotrt:/projectnb/ivc-ml/piotrt",
           "--env", f"CUDA_VISIBLE_DEVICES={sel_gpu}", "--env", "VLLM_NO_USAGE_STATS=1",
           "--env", "HF_HOME=/projectnb/ivc-ml/piotrt/hf_cache",
           SIF, "vllm", "serve", ARBITER_DIR, "--served-model-name", SEL_NAME, "--trust-remote-code",
           "--port", str(PORT), "--max-model-len", "65536", "--gpu-memory-utilization", "0.9", "--dtype", "half"]
    print(f"[online] launching selector vLLM (SIF) on allocated GPU id {sel_gpu}", flush=True)
    p = subprocess.Popen(cmd)
    atexit.register(lambda: p.terminate())
    for _ in range(240):
        try:
            r = requests.get(f"http://localhost:{PORT}/v1/models", timeout=5)
            if r.ok and SEL_NAME in r.text:
                print("[online] selector ready", flush=True); return p
        except Exception:
            pass
        time.sleep(5)
    raise RuntimeError("selector vLLM did not come up")

# ---------------- actor: MolmoWeb + LoRA on GPU0 ----------------
processor = AutoProcessor.from_pretrained(ACTOR_MODEL, trust_remote_code=True, revision=REVISION)
tok = processor.tokenizer

def load_actor():
    base = AutoModelForImageTextToText.from_pretrained(
        ACTOR_MODEL, trust_remote_code=True, torch_dtype=torch.bfloat16,
        attn_implementation="sdpa", revision=REVISION).to(ACTOR_DEV)
    base.config.use_cache = True   # needed for generate; toggled per phase
    _t = os.environ.get("LORA_TARGETS", "all-linear")
    cfg = dict(r=int(os.environ.get("LORA_R", "16")), lora_alpha=int(os.environ.get("LORA_ALPHA", "32")),
               lora_dropout=0.05, target_modules=("all-linear" if _t == "all-linear" else _t.split(",")),
               task_type="CAUSAL_LM")
    cfg["exclude_modules"] = os.environ.get("LORA_EXCLUDE", ".*(vision|visual|vit|image_proj|connector).*")
    model = get_peft_model(base, LoraConfig(**cfg))
    model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": False})
    # NOTE: do NOT enable_input_require_grads -- molmo2 does an in-place merge of image
    # tokens into inputs_embeds, which autograd rejects if the embeddings require grad.
    # use_reentrant=False checkpointing still backprops to the LoRA params without it.
    model.print_trainable_parameters()
    return model

SEQF = ("input_ids", "attention_mask", "mm_token_type_ids")
@torch.no_grad()
def actor_generate(model, states):
    """5 on-policy actions per state, BATCHED: all states x N samples in ONE generate call.
    Sequence fields are LEFT-padded (so generated tokens start at a common offset); image
    fields are repeated N per state. Returns [{raw, action_str, thought}]*N per state."""
    model.eval(); model.config.use_cache = True
    encs = []
    for st in states:
        img = Image.open(st["screenshot"]).convert("RGB")
        msgs = [{"role": "user", "content": [{"type": "text", "text": st["prompt"]},
                                             {"type": "image", "image": img}]}]
        enc = processor.apply_chat_template(msgs, tokenize=True, add_generation_prompt=True,
                                            return_tensors="pt", return_dict=True)
        encs.append({k: (v[0] if k in SEQF else v) for k, v in enc.items() if k != "token_type_ids"})
    maxlen = max(e["input_ids"].shape[0] for e in encs)
    PAD = {"input_ids": tok.pad_token_id or 0, "attention_mask": 0, "mm_token_type_ids": 0}
    seq_rows = {k: [] for k in SEQF if k in encs[0]}; img_rows = {}
    for e in encs:
        for k in seq_rows:
            v = e[k]; p = maxlen - v.shape[0]
            if p > 0:
                v = torch.cat([torch.full((p,), PAD[k], dtype=v.dtype), v])   # LEFT pad
            seq_rows[k].append(v.unsqueeze(0).repeat(N, 1))                    # N samples
        for k, v in e.items():
            if k not in SEQF and torch.is_tensor(v):
                img_rows.setdefault(k, []).append(v.repeat(N, *([1] * (v.dim() - 1))))
    gin = {k: torch.cat(v, 0).to(ACTOR_DEV) for k, v in seq_rows.items()}
    for k, v in img_rows.items():
        gin[k] = torch.cat(v, 0).to(ACTOR_DEV)
    with torch.autocast("cuda", dtype=torch.bfloat16):
        gen = model.generate(**gin, max_new_tokens=512, do_sample=True, temperature=1.0, top_p=1.0, top_k=0)
    new = gen[:, maxlen:]                          # left-pad -> new tokens after a common offset
    out_all = []
    for s in range(len(states)):
        cands = []
        for i in range(N):
            raw = processor.decode(new[s * N + i], skip_special_tokens=True)
            try: thought = json.loads(raw.strip()).get("thought", "")
            except Exception: thought = ""
            cands.append({"raw": raw, "action_str": _action_str(raw), "thought": thought})
        out_all.append(cands)
    del gen, new, gin; torch.cuda.empty_cache()
    return out_all

def _action_str(raw):
    try:
        return MolmoWebAgent._parse_molmo_output(raw)
    except Exception:
        return raw.strip()[:80]

_AGENT = MolmoWebAgent()   # cheap: __init__ doesn't load the model; only for _build_prompt
def actor_prompt(st):
    """Build the actor's native prompt from a raw state (states.jsonl has no prebuilt prompt)."""
    hist = [((h.get("coord") or h.get("action_str") or "").strip(), h.get("thought", "")) for h in st["history"]]
    return _AGENT._build_prompt(st["task"], st["url"], st["step_idx"], hist)

# ---------------- selection via vLLM ----------------
client = OpenAI(base_url=f"http://localhost:{PORT}/v1", api_key="x")
async def select_batch(states, cands_per_state):
    async def one(st, cands):
        sb = open(st["screenshot"], "rb").read()
        traj = [{"action": h.get("coord") or h.get("action_str") or "", "thought": h.get("thought", "")}
                for h in st["history"]]
        reps = []
        for i, k in enumerate(cands):
            ac = ArbiterCandidate(molmo_action=k["action_str"], arbiter_action="", thought=k.get("thought", ""))
            ac._orig = i; reps.append(ac)
        order = list(range(len(reps))); random.Random(st["state_id"]).shuffle(order)
        cl = [{"rep": reps[j], "vote_count": 1, "cluster_key": ("nodom", pos)} for pos, j in enumerate(order)]
        try:
            winner, _, ok = await catts_vision_select_v2(client, SEL_NAME, st["task"], sb, traj, st["url"], cl)
            return getattr(winner, "_orig", 0) if (winner is not None and ok) else 0
        except Exception:
            return 0
    return await asyncio.gather(*(one(st, c) for st, c in zip(states, cands_per_state)))

# ---------------- one SFT step on the selected actions ----------------
def _sft_batch(states, cands_per_state, selected):
    exs = []
    for st, cands, p in zip(states, cands_per_state, selected):
        img = Image.open(st["screenshot"]).convert("RGB")
        user = [{"type": "text", "text": st["prompt"]}, {"type": "image", "image": img}]
        mp = [{"role": "user", "content": user}]
        mf = mp + [{"role": "assistant", "content": [{"type": "text", "text": cands[p]["raw"]}]}]
        full = processor.apply_chat_template(mf, tokenize=True, return_dict=True, return_tensors="pt", add_generation_prompt=False)
        plen = processor.apply_chat_template(mp, tokenize=True, return_dict=True, return_tensors="pt", add_generation_prompt=True)["input_ids"].shape[1]
        ex = {k: (v[0] if k in ("input_ids", "attention_mask", "mm_token_type_ids") else v) for k, v in full.items() if k != "token_type_ids"}
        lab = ex["input_ids"].clone(); lab[:plen] = -100; ex["labels"] = lab
        exs.append(ex)
    # pad + collate
    maxlen = max(e["input_ids"].shape[0] for e in exs)
    PADV = {"input_ids": tok.pad_token_id or 0, "attention_mask": 0, "labels": -100, "mm_token_type_ids": 0}
    seq = [k for k in PADV if k in exs[0]]; b = {k: [] for k in seq}; extra = {}
    for e in exs:
        for k in seq:
            v = e[k]; pad = maxlen - v.shape[0]
            if pad > 0: v = torch.cat([v, torch.full((pad,), PADV[k], dtype=v.dtype)])
            b[k].append(v)
        for k, v in e.items():
            if k not in seq and torch.is_tensor(v): extra.setdefault(k, []).append(v)
    res = {k: torch.stack(v).to(ACTOR_DEV) for k, v in b.items()}
    for k, vs in extra.items(): res[k] = torch.cat(vs, 0).to(ACTOR_DEV)
    return res

def sft_accumulate(model, states, cands, selected, scale):
    """Forward+backward on one SFT micro-batch, scaled for grad accumulation. No opt step."""
    model.train(); model.config.use_cache = False
    batch = _sft_batch(states, cands, selected)
    loss = model(**batch).loss
    (loss * scale).backward()
    return loss.item()

# ---------------- main loop ----------------
def main():
    serve_selector()
    model = load_actor()
    opt = torch.optim.AdamW([p for p in model.parameters() if p.requires_grad], lr=LR)
    states = [json.loads(l) for l in open(STATES_PATH)]
    random.Random(0).shuffle(states)
    # decoupled batch sizes:
    #   ROLLOUT   = states per optimizer step; ALL selected concurrently (amortizes vLLM prefill)
    #   GEN_CHUNK = states generated at once   (KV-cache memory bound)
    #   SFT_BATCH = SFT micro-batch            (training-activation memory bound; grad-accumulated)
    ROLLOUT = int(os.environ.get("ROLLOUT", "24"))
    GEN_CHUNK = int(os.environ.get("GEN_CHUNK", "6"))
    SFT_BATCH = int(os.environ.get("SFT_BATCH", "2"))
    if SMOKE: states = states[:ROLLOUT * 2]
    log = open(f"{OUT}/online.log", "a"); step = 0
    for ep in range(EPOCHS):
        for i in range(0, len(states), ROLLOUT):
            roll = states[i:i + ROLLOUT]
            for st in roll:
                st["prompt"] = actor_prompt(st)
            _t = time.time()
            cands = []                                         # generate in memory-safe sub-chunks
            for g in range(0, len(roll), GEN_CHUNK):
                cands += actor_generate(model, roll[g:g + GEN_CHUNK])
            tgen = time.time() - _t; _t = time.time()
            sel = asyncio.run(select_batch(roll, cands))       # whole rollout concurrent -> efficient
            tsel = time.time() - _t; _t = time.time()
            opt.zero_grad()                                    # SFT micro-batches, grad-accumulated
            n_mb = (len(roll) + SFT_BATCH - 1) // SFT_BATCH
            losses = []
            for j in range(0, len(roll), SFT_BATCH):
                losses.append(sft_accumulate(model, roll[j:j + SFT_BATCH], cands[j:j + SFT_BATCH],
                                             sel[j:j + SFT_BATCH], 1.0 / n_mb))
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0); opt.step()
            tsft = time.time() - _t
            step += 1; loss = sum(losses) / len(losses)
            changed = sum(1 for c, p in zip(cands, sel)
                          if c[p]["action_str"] != max(set(x["action_str"] for x in c),
                                                       key=[x["action_str"] for x in c].count))
            tot = tgen + tsel + tsft
            msg = (f"step {step} ep {ep} roll {len(roll)} loss {loss:.4f} off-plurality {changed}/{len(roll)} "
                   f"| gen {tgen:.1f}s sel {tsel:.1f}s sft {tsft:.1f}s tot {tot:.1f}s ({tot/len(roll):.2f}s/state)")
            print(msg, flush=True); log.write(msg + "\n"); log.flush()
            if not SMOKE and step % int(os.environ.get("SAVE_EVERY", "50")) == 0:
                model.save_pretrained(f"{OUT}/actor_lora_step{step}")
    model.save_pretrained(f"{OUT}/actor_lora")
    print(f"[online] done -> {OUT}/actor_lora", flush=True)


if __name__ == "__main__":
    main()
